### ISSUE TITLE
DEFECT: “Press to collect cash” does not clear the field.

### ISSUE THREAD

**Issue by thushara7** [siddnus/vmcs#1]
The stimulation currently does not clear the values on the completion of a maintenance session after pressing the button “Press to collect cash”

**Comment by siddharthdeshmukh** [comment]
Reset the values to null for “Show Total Cash Held” and “Press to Collect Cash” when the Maintainer successfully pushes “Press Here When Finished”. The simulation currently does not clear the values on the completion of a Maintenance session. Upon a subsequent re-login to the Maintenance Panel in the same session, the cash previously held and already collected, persists in display.

MaintenanceController needs to be fixed for the same.

Moving to the Dev team for the fix

**Comment by sharmamedha** [comment]
Defect has been fixed.
Modified files: MaintainanceController.java

**Comment by Mathura11** [comment]
Tested the application for current defect fix. Application work as usual.
Performed the following testing:
1. Integration test
2. System test
3. Regression Test

**Comment by ShubhanshuGautam** [comment]
Planning to release this bug fix along with the enhancement planned, in the release R1.0.9.

**Comment by thushara7** [comment]
verified the fixture of the same.
