### ISSUE TITLE
Enhancement : Show denomination quantity and its amount.

### ISSUE THREAD

**Issue by thushara7** [siddnus/vmcs#2]
The Maintainer will be able to press “Show Total Cash Held’.  In so doing, a display of not only the Total Cash Held is displayed, the specific Quantity of coins per denomination together with its total cash Amount/value per denomination are calculated and displayed. He should be able to more readily compare the individual Amount by denomination with the Total Cash Held.

**Comment by riteshnus** [comment]
The system is required to provide an at-a-glance display of the cash amount available, by denomination, for collection by the Maintainer. This will enable the Maintainer to readily tally the total cash collected and the total number of coins by denomination displayed in “Show Total Cash Held” and “Press to Collect Cash” when pressed, thus leaving no room for dispute over system errors.

Planned for the next release RC1.0.9
Assigning to Release manager

**Comment by ShubhanshuGautam** [comment]
Creating a new change ticket for the enhancement proposed in CCB meeting.
Created a new branch: R1.0.9 for the development and testing purposes.

Issue assigned to analyst to update HLD for the enhancement.

**Comment by riteshnus** [comment]
This enhancement required to change the GUI of Maintenance panel. It should show the denomination of coins collecting by the maintainer. Also, change GUI how much cash has been collected.

Assigned to Technica Lead.

**Comment by siddharthdeshmukh** [comment]
HLD updated by Ritesh. 
Assigning the issue to developer for Implementation.

**Comment by sharmamedha** [comment]
Enhancement on "Show denomination quantity and its amount" implemented.
Modified Files:
CoinDisplay.java
CoinLabelItem.java
CoinLabelItemDisplay.java
MaintenanceController.java
MaintenancePanel.java
StoreController.java
TotalCashButtonListener.java

Unit testing is completed.

Asssigning to QA team.

**Comment by Mathura11** [comment]
Performed integration and system test after the enhancement implementation and application works fine.

Reviewed the UCMS document.

assigned for UAT.

**Comment by thushara7** [comment]
Performed the User acceptance Test.
All the features added as an enhancement are accepted.

**Comment by ShubhanshuGautam** [comment]
Created a tag R1.0.9 for the release of enhancement done and bug fixes.

**Comment by riteshnus** [comment]
verified the fixture of the same. 

The release went to production without defect.

**Comment by riteshnus** [comment]
Closed the CR.
